version: "3.7"
services:
  db:
    restart: always
    image: postgres:13
    ports:
      - 8900:5432
    environment:
      POSTGRES_DB: pjwstk
      POSTGRES_USER: pjwstk
      POSTGRES_PASSWORD: pjwstk!123

  cluster:
    image: ipfs/ipfs-cluster
    volumes:
      - /var/ipfs/cluster:/data/ipfs-cluster
#    env_file: /var/data/config/ipfs/ipfs.env
    ports:
      - 9095:9095
      - 9096:9096
    depends_on:
      - daemon

  daemon:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - /var/ipfs/daemon:/data/ipfs
